import React from 'react';
import { casteThemes } from '../data/talents';
export { casteThemes } from '../data/talents';
export function Logo({size=170}){return <img src="/tsaak-logo.jpg" alt="TSAAK" style={{width:size, maxWidth:'80%', objectFit:'contain', filter:'drop-shadow(0 0 28px rgba(0,229,255,.45))'}}/>}
export function LetterMark({caste}){const t=casteThemes[caste]||casteThemes.media;return <div style={{position:'absolute',top:22,right:24,width:38,height:38,borderRadius:14,border:`1px solid ${t.color}`,color:t.color,display:'grid',placeItems:'center',fontWeight:900,boxShadow:`0 0 20px ${t.color}66`}}>{t.letter}</div>}
export function pageStyle(caste='media'){const t=casteThemes[caste]||casteThemes.media;return {minHeight:'100vh',color:'white',fontFamily:'Inter,Arial,sans-serif',background:`radial-gradient(circle at 15% 5%, ${t.color}30, transparent 28%), radial-gradient(circle at 85% 15%, #0a0d1f, #03040A 60%)`,padding:'0 0 60px'}}
export function topNav(caste='media'){return <nav style={{display:'flex',gap:18,alignItems:'center',maxWidth:1180,margin:'0 auto',padding:'24px 28px',borderBottom:'1px solid rgba(255,255,255,.08)'}}><a href="/" style={navLink()}>Home</a><a href="/demo" style={navLink()}>Demo</a><a href="/search" style={navLink()}>Recherche IA</a><a href="/wanted" style={navLink()}>Wanted</a><a href="/help-me" style={navLink()}>Help Me</a><a href="/messaging" style={navLink()}>Messages</a></nav>}
function navLink(){return {color:'#cbd5e1',textDecoration:'none',fontSize:14}}
export function CasteShell({caste='media',person,children}){const t=casteThemes[caste]||casteThemes.media;return <main style={pageStyle(caste)}><LetterMark caste={caste}/>{topNav(caste)}<section style={{maxWidth:1180,margin:'0 auto',padding:28}}>{person&&<div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:20,margin:'16px 0 28px'}}><div><div style={{color:t.color,fontSize:13,fontWeight:800,letterSpacing:2,textTransform:'uppercase'}}>{t.name} cockpit</div><h1 style={{fontSize:44,margin:'8px 0'}}>Salut {person.name.split(' ')[0]} 👋</h1><p style={{color:'#a7b0c2',fontSize:18,margin:0}}>{person.greeting||'Bonne nouvelle : ton espace TSAAK a des opportunités à traiter.'}</p></div><Avatar src={person.avatar} name={person.name} role={person.role} big/></div>}{children}</section></main>}
export function Avatar({src,name,role,big=false}){return <div style={{display:'flex',alignItems:'center',gap:14}}><img src={src} alt={name} style={{width:big?74:44,height:big?74:44,borderRadius:24,objectFit:'cover',border:'1px solid rgba(255,255,255,.18)'}}/><div><b>{name}</b>{role&&<div style={{color:'#94a3b8',fontSize:13}}>{role}</div>}</div></div>}
export function Card({children,tone}){return <div style={card(tone)}>{children}</div>}
export function Button({children,href,tone}){const el=<span style={button(tone)}>{children}</span>;return href?<a href={href} style={{textDecoration:'none'}}>{el}</a>:el}
export function Stat({label,value,tone}){return <div style={{padding:18,borderRadius:20,background:'rgba(255,255,255,.045)',border:`1px solid ${tone||'rgba(255,255,255,.12)'}`}}><div style={{fontSize:12,color:'#94a3b8'}}>{label}</div><div style={{fontSize:30,fontWeight:900}}>{value}</div></div>}
export function StatusRail({items=['Open','Proposals','Shortlist','Contact','Accepted'],active=2,tone='#00E5FF'}){return <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{items.map((x,i)=><span key={x} style={{padding:'9px 12px',borderRadius:999,border:`1px solid ${i<=active?tone:'rgba(255,255,255,.14)'}`,color:i<=active?'white':'#64748b',background:i===active?`${tone}22`:'transparent'}}>{x}</span>)}</div>}
export function TsaakLogo(){return <Logo size={190}/>}
export function card(tone){return {padding:24,borderRadius:28,background:'linear-gradient(145deg,rgba(255,255,255,.08),rgba(255,255,255,.03))',border:`1px solid ${tone||'rgba(255,255,255,.12)'}`,boxShadow:'0 24px 90px rgba(0,0,0,.35)',backdropFilter:'blur(18px)'}}
export function button(tone='#00E5FF'){return {display:'inline-block',padding:'13px 18px',borderRadius:16,color:'white',fontWeight:800,border:`1px solid ${tone}`,background:`linear-gradient(90deg,${tone}55,rgba(255,255,255,.06))`,boxShadow:`0 0 30px ${tone}33`,marginRight:10,marginTop:10,cursor:'pointer'}}
export function ghostButton(tone='#fff'){return {...button(tone),background:'rgba(255,255,255,.04)',boxShadow:'none'}}
export const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:18};
export const muted={color:'#94a3b8'};
export const input={width:'100%',padding:16,borderRadius:18,background:'rgba(255,255,255,.06)',color:'white',border:'1px solid rgba(255,255,255,.12)',boxSizing:'border-box'};
